from django.urls import path
from . import views

urlpatterns = [
    path('ping', views.ping, name='ping'),
    path('login', views.login_api_view, name='login'),
    path('logout', views.logout_api_view, name='logout'),
    path('user_info', views.user_info_view, name='user_info'),
    path('get_user', views.get_user_view, name='get_user'),
    path('list_user', views.list_user_view, name='list_user'),
    path('add_user', views.add_user_view, name='add_user'),
    path('update_user', views.update_user_view, name='update_user'),
    path('get_lab', views.get_lab_view, name='get_lab'),
    path('list_lab', views.list_lab_view, name='list_lab'),
    path('add_lab', views.add_lab_view, name='add_lab'),
    path('update_lab', views.update_lab_view, name='update_lab'),
    path('get_course', views.get_course_view, name='get_course'),
    path('list_course', views.list_course_view, name='list_course'),
    path('add_course', views.add_course_view, name='add_course'),
    path('update_course', views.update_course_view, name='update_course'),
    path('get_group', views.get_group_view, name='get_group'),
    path('list_group', views.list_group_view, name='list_group'),
    path('add_group', views.add_group_view, name='add_group'),
    path('update_group', views.update_group_view, name='update_group'),
    path('get_session', views.get_session_view, name='get_session'),
    path('list_session', views.list_session_view, name='list_session'),
    path('add_regular_session', views.add_regular_session_view,
         name='add_regular_session'),
    path('add_special_session', views.add_special_session_view,
         name='add_special_session'),
    path('update_session', views.update_session_view, name='update_session'),
    path('get_record', views.get_record_view, name='get_record'),
    path('list_record', views.list_record_view, name='list_record'),
    path('update_record', views.update_record_view, name='update_record'),
    path('list_record_filters', views.list_record_filters_view,
         name='list_record_filters'),
]
