# Generated by Django 4.1 on 2022-09-14 17:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('be_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkinrecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_records', to=settings.AUTH_USER_MODEL),
        ),
    ]
