# Generated by Django 4.1 on 2022-09-11 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('be_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='week',
            name='monday_date',
            field=models.DateField(),
        ),
    ]
