# Generated by Django 4.1 on 2022-09-12 15:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('be_api', '0002_alter_week_monday_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=128)),
                ('email', models.CharField(max_length=128)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_ta', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='basesession',
            name='make_up_students',
            field=models.ManyToManyField(related_name='sessions_to_make_up', through='be_api.MakeUpSession', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_coordinators',
            field=models.ManyToManyField(related_name='course_coordinator_of', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='group',
            name='students',
            field=models.ManyToManyField(related_name='student_of', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='group',
            name='teaching_assistants',
            field=models.ManyToManyField(related_name='teaching_assistant_of', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lab',
            name='lab_executives',
            field=models.ManyToManyField(related_name='lab_executive_of', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='makeupsession',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='make_up_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
