# Generated by Django 4.1 on 2022-09-12 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('be_api', '0003_profile_alter_basesession_make_up_students_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_admin',
        ),
    ]
